service: creativeai

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  region: eu-north-1
  stage: prod
  profile: serverless-admin


  iamRoleStatements:
    - Effect: Allow
      Action:
      - s3:PutObject
      - s3:PutObjectAcl
      - s3:GetObject
      - s3:ListBucket
      Resource:
      - arn:aws:s3:::creative-ai-bucket/*
      - arn:aws:s3:::creative-ai-bucket


plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: any
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

package:
  individually: true
  patterns:
    - '!tests/**'
    - '!docs/**'
    - '!*.md'
    - '!*.log'

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    target: node18
    platform: node
    concurrency: 10
