// Define your messages
const messages = {
    emailAlreadyExists: 'The email address is already in use.',
    userRegistered: 'User registration successful.',
    internalServerError: 'An internal server error occurred.',
    accountNotFound: "Account not found. Please check your details.",
    invalidPassword: "Invalid password.",
    loginSuccess: 'Login successfully.',
    emailNotFound: 'Email address not found. Please enter a valid email.',
    passwordResetLinkSentSuccesfully: 'Password reset link sent to your email.',
    currentPasswordIncorrect: 'Current password is incorrect.',
    dataNotFound: "Data not found",
    passwordChanged: "Password changed successfully",
    passwordNotChanged: "Password not changed",
    passwordsDoNotMatch: 'Passwords do not match.',
    dataFoundSuccessful: 'Data found successfully',
    freeDemoRegistered: 'Free demo registration successful.',
    freeDemoNotFound: "No users found for the free demo.",
    idRequire: "Id must be require",
    dataAddedSuccessfull: "Data Added Sucessfully",
    freeDemoNotFoundOnGivenId: "No user found for the given ID in the free demo.",
    scheduleAdded: 'Schedule added successfully.',
    serverRunning: 'Node app is running on the specified port',
    passwordResetLink: "Please click the link below to reset your password.",
    passwordResetSubject: "Password Reset Request",
    invalidLink: "Invalid link. Please request a new one.",
    pageNotFound: "404 Error, Page Not Found",
    errorToSendingEmail: "Error sending email",
    dbConnectionError: 'Error when connecting to db:',
    dbConnectionSuccess: 'Connected to MySQL Server!',
    dbConnectionClosing: 'Closing database connection',
    dbError: 'Database connection error:',
    protocolConnectionLost: 'Database connection was lost. Reconnecting...',
    NO_TOKEN_PROVIDED: 'Unauthorized: No token provided',
    INVALID_OR_MISSING_TOKEN: 'Unauthorized: Invalid or missing token',
    INVALID_TOKEN: 'Unauthorized: Invalid token',
    USER_NOT_FOUND: 'User Not Found',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    BILLING_INFO_ADD: "Your billing information has been saved successfully.",
    dataNotAdded: "Data could not be added. Please try again or check your input.",
    projectNotFound: "No projects found for this user. Please add a project to proceed.",
    projectAdded: "Project added successfully.",
    projectUpdated: "Project updated successfully.",
    projectDeleted: "Project deleted successfully.",
    projectNotUpdated: "Project could not be updated. Please try again or check your input.",
    projectNotDeleted: "Project could not be deleted. Please try again or check your input.",
    projectNotFoundOnGivenId: "No project found for the given ID.",
    
};

// Export the messages
export default messages;
